packages:
  - packages/*
  - internal/*
  - venues/*

catalog:
  concurrently: ^9.2.1
  copy-webpack-plugin: ^13.0.1
  css-loader: ^7.1.2
  es-toolkit: ^1.43.0
  fork-ts-checker-webpack-plugin: ^9.1.0
  html-webpack-plugin: ^5.6.5
  mini-css-extract-plugin: ^2.10.0
  postcss: ^8.5.6
  postcss-preset-env: ^10.6.0
  sass: ^1.97.2
  sass-loader: ^16.0.6
  style-loader: ^4.0.0
  ts-loader: ^9.5.4
  tsconfig-paths-webpack-plugin: ^4.2.0
  typescript: ^5.9.3
  webpack: ^5.104.1
  webpack-cli: ^6.0.1
  webpack-dev-server: 5.2.2
  webpack-merge: ^6.0.1

catalogMode: prefer

catalogs:
  build:
    esbuild: ^0.27.2
  types:
    '@types/node': ^25.0.9
    type-fest: ^5.4.1
