packages:
  - packages/*
  - internal/*
  - venues/*

catalog:
  concurrently: ^9.2.1
  css-loader: ^7.1.2
  html-webpack-plugin: ^5.6.5
  postcss: ^8.5.6
  postcss-preset-env: ^10.6.0
  sass: ^1.97.2
  sass-loader: ^16.0.6
  style-loader: ^4.0.0
  webpack: ^5.104.1
  webpack-cli: ^6.0.1
  webpack-dev-server: 5.2.2
  webpack-merge: ^6.0.1

catalogMode: prefer
